### GETTING SOME DATA
GET http://localhost:4000/data/cover/1

### Getting more data
GET http://localhost:4000/data/content/TeannaTrump

### Getting Media data 
GET http://localhost:4000/data/media/Maplestar_Art/3

### Searching Data
GET http://localhost:4000/data/search/b/1